- name: Block pkexec with empty first argument with systemtap
  hosts: all
  become: true

  tasks:
    - name: Install systemtap packages
      yum:
        name:
          - systemtap
          - yum-utils
          - kernel-devel-{{ ansible_kernel }}

    - when: ansible_distribution_major_version == '7'
      name: (RHEL 7) Install kernel debuginfo
      command: debuginfo-install -y kernel-{{ ansible_kernel }}

    - when: (ansible_distribution_major_version == '6' or
             ansible_distribution_major_version == '8')
      name: (RHEL 6/8) Install polkit debuginfo
      command: debuginfo-install -y polkit

    # RHEL6 with SELinux enabled needs libselinux-python for Ansible copy operation to work.
    - when: ansible_distribution_major_version == '6'
      name: (RHEL 6) Install libselinux-python
      yum:
        name:
          - libselinux-python

    - name: Create systemtap script
      copy:
        dest: /root/pkexec-block.stp
        owner: root
        group: root
        mode: '0600'
        force: false
        content: |
          probe process("/usr/bin/pkexec").function("main")  {
            if (cmdline_arg(1) == "")
              raise(9);
          }

    - name: Checking if stap_pkexec_block module is already loaded
      command: grep -Fq stap_pkexec_block /proc/modules
      register: loaded_module
      changed_when: false
      failed_when: loaded_module.rc == 2
      check_mode: false

    - when: loaded_module.rc == 1
      name: Install systemtap script
      command: stap -F -o /root/pkexec-block.log -S 1 -m stap_pkexec_block -g /root/pkexec-block.stp
...
