- hosts: 10.92.192.250                                                 
                                                                       
  tasks:                                                               
                                                                       
                                                                       
    - name: change default chain policy (used to clean rules)          
      iptables:                                                        
        chain: INPUT                                                   
        policy: ACCEPT                                                 
                                                                       
    - name: clean rules on all chains of filter table                  
      iptables:                                                        
        table: filter                                                  
        flush: yes                                                     
                                                                       
    - name: delete all user-defined chains on filter table             
      shell: iptables -t filter -X                                     
                                                                       
    - name: Allow packages to loopback interface                       
      iptables:                                                        
        in_interface: lo                                               
        chain: INPUT                                                   
        jump: ACCEPT                                                   
        comment: loopback                                              
                                                                       
    - name: Allow established state                                    
      iptables:                                                        
        chain: INPUT                                                   
        ctstate: ESTABLISHED                                           
        jump: ACCEPT                                                   
                                                                       
    - name: Allow ssh connection                                       
      iptables:                                                        
        chain: INPUT                                                   
        src_range: 10.92.192.0/24                                      
        protocol: tcp                                                  
        destination_port: '22'                                         
        jump: ACCEPT                                                   
        comment: ssh                                                   
                                                                       
    - name: Allow http connection                                      
      iptables:                                                        
        chain: INPUT                                                   
        source: 192.168.1.0/24                                         
        protocol: tcp                                                  
        destination_port: '80'                                         
        jump: ACCEPT                                                   
        comment: http                                                  
                                                                       
    - name: Allow ftp connection                                       
      iptables:                                                        
        chain: INPUT                                                   
        protocol: tcp                                                  
        source_port: "{{ item }}"                                      
        jump: ACCEPT                                                   
        comment: ftp                                                   
      with_items: [ '20', '21' ]                                       
                                                                       
    - name: set default chain policy                                   
      iptables:                                                        
        chain: INPUT                                                   
        policy: DROP                                                   
                                                                       
                                                                       
                                                                       
    - name: clean rules on all chains of nat table                     
      iptables:                                                        
        table: nat                                                     
        flush: yes                                                     
                                                                       
    - name: delete all user-defined chains on nat table                
      shell: iptables -t nat -X                                        
                                                                       
    - name: masquerade connection                                      
      shell: iptables -t nat -A POSTROUTING -o ppp0 -j MASQUERADE      
                                                                       
